---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-15.04

suites:
  - name: default
    run_list:
      - "mydevmachine::default"
    attributes:
