---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  product_version: 14
  client_rb:
    chef_license: accept

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - "mydevmachine::default"
    attributes:
