name             'mydevmachine'
maintainer       'Giovanni Toraldo'
maintainer_email 'me@gionn.net'
license          'Apache2'
description      'Configures my dev machine'
long_description 'Configures my dev machine'
version          '0.1.0'

depends          'apt'
depends          'java'
depends          'prezto'
depends          'ruby_rbenv'
depends          'pyenv'
depends          'nvm'
depends          'vagrant'
