name             'mydevmachine'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mydevmachine'
long_description 'Installs/Configures mydevmachine'
version          '0.1.0'

depends          'apt', '~> 2.6.1'
depends          'users', '~> 1.7.1'
depends          'java', '~> 1.31.0'
depends          'prezto', '~> 0.1.4'
depends          'rbenv', '~> 0.7.3'
depends          'ruby_build', '~> 0.8.0'
depends          'pyenv', '~> 0.1.0'
depends          'nodejs', '~> 2.2.0'
